### PR TITLE
Swizzle version banner

### LINKED ISSUE #1576: Fix version banners
**Describe the bug**

Currently our version banners where you can use arbitrary markdown are broken.
One way to fix this, would be going back to an easier [initial version](https://github.com/iotaledger/iota-wiki/pull/1093), as we basically have no clue how to fix the current version.

### PR DESCRIPTION
**Pull request by Dr-Electron**
# Description of change

This is basically a rebase of #1093. I didn't add the deprecated banner tho. We can still add it if we see the need for it

## Links to any relevant issues

Fixes #1576. (hopefully :trollface: )

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## Change checklist

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [x] I have made sure that added/changed links still work
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by Dr-Electron** [comment]
Seems to work. Tested in https://github.com/iotaledger/iota-wiki/pull/1567.

Maybe instead of adding a deprecated banner like we did in the past, what about adding a `staging` banner?
It could say something like
```
This is an upcoming version currently deployed on our staging Network Shimmer, for up-to-date …
```

File: src/theme/DocVersionBanner/index.tsx [hunk 1]
```diff
@@ -0,0 +1,179 @@
...
+              >
+                latest version
+              </Translate>
+            </Link>
+          </b>
+        ),
+      }}
+    >
+      {
+        'For up-to-date documentation, see the {latestVersionLink} ({versionLabel}).'
```
Comment (jlvandenhout) [inline src/theme/DocVersionBanner/index.tsx:109]: Currently the text feels a bit weird, saying 'up-to-date' pointing to an older version. I'd change it to something like:

```suggestion
        'For the latest stable release, see the {latestVersionLink} ({versionLabel}).'
```

File: src/utils/pluginConfigGenerators.js [hunk 2]
```diff
@@ -43,6 +43,7 @@ function generatePluginConfig(pluginConfig, basePath) {
                   label,
                   path: mainVersion.label === label ? undefined : label,
                   badge: true,
+                  banner: banner,
```
Comment (jlvandenhout) [inline src/utils/pluginConfigGenerators.js:46]:
```suggestion
                  banner,
```

File: src/plugins/docs/index.js [hunk 3]
```diff
@@ -136,15 +89,46 @@ async function pluginDocs(context, options) {
...
+function validateOptions({ validate, options }) {
+  const { versions = {}, globalSidebars = [], ...docsOptions } = options;
+  const versionEntries = Object.entries(versions);
+  if (versionEntries.length > 1)
+    throw 'Multiple Docusuaurus doc versions not allowed in the Wiki';
+  // Handle version banner.
+  const versionBannerMap = {};
+  const docsVersionEntries = versionEntries.map(
+    ([versionLabel, versionOptions]) => {
+      // TODO: validate banner
```
Comment (lucas-tortora) [inline src/plugins/docs/index.js:102]: just in case, there's a todo here

**Review by lucas-tortora — APPROVED** [review]
Nothing to add to Jeroen's review

**Comment by lucas-tortora** [comment]
> Seems to work. Tested in #1567.
> 
> Maybe instead of adding a deprecated banner like we did in the past, what about adding a `staging` banner? It could say something like
> 
> ```
> This is an upcoming version currently deployed on our staging Network Shimmer, for up-to-date …
> ```

If it's no trouble, I see no reason why not. Though I wouldn't spend too much time on this at the moment.

File: src/plugins/docs/index.js (hunk 3 above)
Comment (Dr-Electron) [reply src/plugins/docs/index.js:102]: @jlvandenhout it is your todo. No clue what you wanted to do here 😆

File: src/theme/DocVersionBanner/index.tsx (hunk 1 above)
Comment (Dr-Electron) [reply src/theme/DocVersionBanner/index.tsx:109]: It is what docusaurus does. But yeah we can change it

File: src/theme/DocVersionBanner/index.tsx [hunk 4]
```diff
@@ -0,0 +1,179 @@
+/**
+ * SWIZZLED VERSION: 2.4.3
+ * REASONS:
+ *  - Remove use of siteTitle as it is irrelevant in our setup.
+ *  - Link to our own latest version.
```
Comment (Dr-Electron) [inline src/theme/DocVersionBanner/index.tsx:5]:
```suggestion
 *  - Link to our own latest version.
 *  - Update text
```

**Comment by Dr-Electron** [comment]
> > Seems to work. Tested in #1567.
> > Maybe instead of adding a deprecated banner like we did in the past, what about adding a `staging` banner? It could say something like
> > ```
> > This is an upcoming version currently deployed on our staging Network Shimmer, for up-to-date …
> > ```
> 
> If it's no trouble, I see no reason why not. Though I wouldn't spend too much time on this at the moment.

It is like 2min of work ;)
Can you suggest some text for it?

File: src/plugins/docs/index.js (hunk 3 above)
Comment (jlvandenhout) [reply src/plugins/docs/index.js:102]: Normally you'd validate config in this function, but since the valid values of `banner` are hardcoded, it would fail with our additional values. So we take `banner` out of the options, before they are validated, and then re-add `banner` after valodation. I'm fine merging this as is.

**Review by jlvandenhout — APPROVED** [review]

**Comment by lucas-tortora** [comment]
> > > Seems to work. Tested in #1567.
> > > Maybe instead of adding a deprecated banner like we did in the past, what about adding a `staging` banner? It could say something like
> > > ```
> > > This is an upcoming version currently deployed on our staging Network Shimmer, for up-to-date …
> > > ```
> > 
> > 
> > If it's no trouble, I see no reason why not. Though I wouldn't spend too much time on this at the moment.
> 
> It is like 2min of work ;) Can you suggest some text for it?

`The current documentation is only applicable to the Shimmer staging network. The described features and functionalities are under testing and may differ from the IOTA network.`
